### ISSUE TITLE
Transfer to the atom org

### ISSUE THREAD

**Issue by benogle** [eqot/autocomplete-unicode-emojis#3]
Would you mind transferring this to the atom org? I'd like to release a bundled autocomplete this week with this repo included

**Comment by benogle** [comment]
I'll keep you as a collaborator. Thanks a bunch for taking this on! :tada:

**Comment by eqot** [comment]
Yes, I am glad to hear that.
But, just in case, let me check one thing. Do you mean [autocomplete-emojis](https://github.com/eqot/autocomplete-emojis) instead of this package?

This package was implemented but eventually its functionality has been merged into [autocomplete-emojis](https://github.com/eqot/autocomplete-emojis). Sorry to confuse you...

**Comment by benogle** [comment]
Yes, then autocomplete-emoji

**Comment by eqot** [comment]
OK.
I do not understand if I should do something to transfer autocomplete-emojis to the atom org at github.com and atom.io, and how.
If I should do something, please let me know.

**Comment by benogle** [comment]
Can you add me as an admin / collaborator on the autocomplete-emojis repo?

**Comment by eqot** [comment]
I have added you as a collaborator. Is it ok?

**Comment by benogle** [comment]
So turns out you will need to transfer ownership to my account `benogle`, then I can transfer it to atom. 

![transfer](https://cloud.githubusercontent.com/assets/69169/7578571/8a8e5dd6-f80b-11e4-8970-f6855fd5afab.jpg)

**Comment by eqot** [comment]
Hmmm, I tried but it shows an error of 'benogle/autocomplete-emojis already exists'.
You seem to already have it...
Is it possible to remove your (forked?) repo, first?

**Comment by benogle** [comment]
Ha. Deleted. Thanks for your patience. This is more complicated than I thought.

**Comment by eqot** [comment]
Thanks. I have done.

**Comment by benogle** [comment]
Thank you!

**Comment by benogle** [comment]
All done! https://github.com/atom/autocomplete-emojis

**Comment by eqot** [comment]
Yes, it looks perfect.
On the other hand, [autocomplete-emojis at atom.io](https://atom.io/packages/autocomplete-emojis) still have links to eqot/autocomplete-emojis, like 'Repo' and 'Bugs'.
Are you going to do something for atom.io as well?

**Comment by benogle** [comment]
I'll publish a new version with new links

**Comment by eqot** [comment]
Sounds perfect.
Thank you very much! :smile:

**Comment by benogle** [comment]
New release published. Thanks again.
